// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) Alphawave IP Inc. All rights reserved.
 */

#ifndef __aw_alphacore_atest_defines
#define __aw_alphacore_atest_defines

#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VREF_ADDR  1
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VREF_TERM  0
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VREF_NOM  0.491
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VREF_TOL  3

#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VBOOST_ADDR  2
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VBOOST_TERM  0
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VBOOST_NOM  0.397
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VBOOST_TOL  20

#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VCHARGE_ADDR  3
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VCHARGE_TERM  0
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VCHARGE_NOM  0.405
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VCHARGE_TOL  10

#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VDDREG_ADDR  4
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VDDREG_TERM  0
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VDDREG_NOM  0.736
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VDDREG_TOL  5

#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VDDH_ADDR  5
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VDDH_TERM  3
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VDDH_NOM  1.2
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VDDH_TOL  10

#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VSS_ADDR  6
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VSS_TERM  4
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VSS_NOM  0
#define AW_ATEST_CMN_REGULATOR_HSREFBUF_VSS_TOL  10

#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VREF_ADDR  7
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VREF_TERM  0
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VREF_NOM  0.491
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VREF_TOL  3

#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VBOOST_ADDR  8
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VBOOST_TERM  0
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VBOOST_NOM  0.396
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VBOOST_TOL  20

#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VCHARGE_ADDR  9
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VCHARGE_TERM  0
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VCHARGE_NOM  0.405
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VCHARGE_TOL  10

#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VDDREG_ADDR  10
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VDDREG_TERM  0
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VDDREG_NOM  0.736
#define AW_ATEST_CMN_REGULATOR_LSREFBUF_VDDREG_TOL  5

#define AW_ATEST_CMN_LEVELSHIFTER_P_VDD_ADDR  11
#define AW_ATEST_CMN_LEVELSHIFTER_P_VDD_TERM  0
#define AW_ATEST_CMN_LEVELSHIFTER_P_VDD_NOM  0.7
#define AW_ATEST_CMN_LEVELSHIFTER_P_VDD_TOL  10

#define AW_ATEST_CMN_LEVELSHIFTER_P_VSS_ADDR  12
#define AW_ATEST_CMN_LEVELSHIFTER_P_VSS_TERM  4
#define AW_ATEST_CMN_LEVELSHIFTER_P_VSS_NOM  0
#define AW_ATEST_CMN_LEVELSHIFTER_P_VSS_TOL  10

#define AW_ATEST_CMN_BANDGAP_VDDH_ADDR  13
#define AW_ATEST_CMN_BANDGAP_VDDH_TERM  3
#define AW_ATEST_CMN_BANDGAP_VDDH_NOM  1.2
#define AW_ATEST_CMN_BANDGAP_VDDH_TOL  10

#define AW_ATEST_CMN_BANDGAP_VC_ADDR  14
#define AW_ATEST_CMN_BANDGAP_VC_TERM  0
#define AW_ATEST_CMN_BANDGAP_VC_NOM  0.637
#define AW_ATEST_CMN_BANDGAP_VC_TOL  10

#define AW_ATEST_CMN_BANDGAP_VB_ADDR  15
#define AW_ATEST_CMN_BANDGAP_VB_TERM  0
#define AW_ATEST_CMN_BANDGAP_VB_NOM  0.707
#define AW_ATEST_CMN_BANDGAP_VB_TOL  10

#define AW_ATEST_CMN_BANDGAP_VREF2_ADDR  16
#define AW_ATEST_CMN_BANDGAP_VREF2_TERM  0
#define AW_ATEST_CMN_BANDGAP_VREF2_NOM  0.393
#define AW_ATEST_CMN_BANDGAP_VREF2_TOL  10

#define AW_ATEST_CMN_BANDGAP_VREF_ADDR  17
#define AW_ATEST_CMN_BANDGAP_VREF_TERM  0
#define AW_ATEST_CMN_BANDGAP_VREF_NOM  0.708
#define AW_ATEST_CMN_BANDGAP_VREF_TOL  10

#define AW_ATEST_CMN_BANDGAP_VSS_ADDR  18
#define AW_ATEST_CMN_BANDGAP_VSS_TERM  4
#define AW_ATEST_CMN_BANDGAP_VSS_NOM  0
#define AW_ATEST_CMN_BANDGAP_VSS_TOL  10

#define AW_ATEST_CMN_CLOCKGEN_VREF_ADDR  19
#define AW_ATEST_CMN_CLOCKGEN_VREF_TERM  0
#define AW_ATEST_CMN_CLOCKGEN_VREF_NOM  0.49
#define AW_ATEST_CMN_CLOCKGEN_VREF_TOL  3

#define AW_ATEST_CMN_CLOCKGEN_VBOOST_ADDR  20
#define AW_ATEST_CMN_CLOCKGEN_VBOOST_TERM  0
#define AW_ATEST_CMN_CLOCKGEN_VBOOST_NOM  0.612
#define AW_ATEST_CMN_CLOCKGEN_VBOOST_TOL  20

#define AW_ATEST_CMN_CLOCKGEN_VCHARGE_ADDR  21
#define AW_ATEST_CMN_CLOCKGEN_VCHARGE_TERM  0
#define AW_ATEST_CMN_CLOCKGEN_VCHARGE_NOM  0.405
#define AW_ATEST_CMN_CLOCKGEN_VCHARGE_TOL  10

#define AW_ATEST_CMN_CLOCKGEN_VDDREG_ADDR  22
#define AW_ATEST_CMN_CLOCKGEN_VDDREG_TERM  0
#define AW_ATEST_CMN_CLOCKGEN_VDDREG_NOM  0.931
#define AW_ATEST_CMN_CLOCKGEN_VDDREG_TOL  5

#define AW_ATEST_CMN_CLOCKGEN_VB1_ADDR  23
#define AW_ATEST_CMN_CLOCKGEN_VB1_TERM  0
#define AW_ATEST_CMN_CLOCKGEN_VB1_NOM  0.455
#define AW_ATEST_CMN_CLOCKGEN_VB1_TOL  10

#define AW_ATEST_CMN_CLOCKGEN_VB2_ADDR  24
#define AW_ATEST_CMN_CLOCKGEN_VB2_TERM  0
#define AW_ATEST_CMN_CLOCKGEN_VB2_NOM  0.41
#define AW_ATEST_CMN_CLOCKGEN_VB2_TOL  10

#define AW_ATEST_CMN_THERMCAL_IB_ADDR  25
#define AW_ATEST_CMN_THERMCAL_IB_TERM  0
#define AW_ATEST_CMN_THERMCAL_IB_NOM  NC
#define AW_ATEST_CMN_THERMCAL_IB_TOL  10

#define AW_ATEST_CMN_THERMCAL_VB1_ADDR  26
#define AW_ATEST_CMN_THERMCAL_VB1_TERM  0
#define AW_ATEST_CMN_THERMCAL_VB1_NOM  NC
#define AW_ATEST_CMN_THERMCAL_VB1_TOL  10

#define AW_ATEST_CMN_LSREF_VB1_ADDR  27
#define AW_ATEST_CMN_LSREF_VB1_TERM  0
#define AW_ATEST_CMN_LSREF_VB1_NOM  0.738
#define AW_ATEST_CMN_LSREF_VB1_TOL  10

#define AW_ATEST_CMN_LSREF_VB2_ADDR  28
#define AW_ATEST_CMN_LSREF_VB2_TERM  0
#define AW_ATEST_CMN_LSREF_VB2_NOM  NC
#define AW_ATEST_CMN_LSREF_VB2_TOL  10

#define AW_ATEST_CMN_HSREF_VB1_ADDR  29
#define AW_ATEST_CMN_HSREF_VB1_TERM  0
#define AW_ATEST_CMN_HSREF_VB1_NOM  NC
#define AW_ATEST_CMN_HSREF_VB1_TOL  10

#define AW_ATEST_CMN_HSREF_VB2_ADDR  30
#define AW_ATEST_CMN_HSREF_VB2_TERM  0
#define AW_ATEST_CMN_HSREF_VB2_NOM  NC
#define AW_ATEST_CMN_HSREF_VB2_TOL  10

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_REPLICA_LSB_ADDR  1
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_REPLICA_LSB_TERM  0
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_REPLICA_LSB_NOM  1.2
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_REPLICA_LSB_TOL  10

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_OVR_LSB_ADDR  2
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_OVR_LSB_TERM  0
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_OVR_LSB_NOM  0.8
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_OVR_LSB_TOL  20

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_MSB_ADDR  3
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_MSB_TERM  0
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_MSB_NOM  0.8
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VGP_MSB_TOL  20

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_PA_VDDH_GATED_ADDR  4
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_PA_VDDH_GATED_TERM  3
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_PA_VDDH_GATED_NOM  1.2
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_PA_VDDH_GATED_TOL  10

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_PA_VSS_ADDR  5
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_PA_VSS_TERM  4
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_PA_VSS_NOM  0
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_PA_VSS_TOL  20

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_PART_M_ADDR  6
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_PART_M_TERM  0
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_PART_M_NOM  NC
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_PART_M_TOL  20

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_VCM_ADDR  7
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_VCM_TERM  0
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_VCM_NOM  NC
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_VCM_TOL  20

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_PART_P_ADDR  8
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_PART_P_TERM  0
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_PART_P_NOM  NC
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_PART_P_TOL  20

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_FULL_P_ADDR  9
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_FULL_P_TERM  0
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_FULL_P_NOM  NC
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_11_FULL_P_TOL  20

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VSAFE_CASCODE_ADDR  10
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VSAFE_CASCODE_TERM  0
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VSAFE_CASCODE_NOM  NC
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_VSAFE_CASCODE_TOL  20

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_IBAISP_SENSE_LSB_ADDR  11
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_IBAISP_SENSE_LSB_TERM  2
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_IBAISP_SENSE_LSB_NOM  1.2
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_IBAISP_SENSE_LSB_TOL  20

#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_IBIASP_SENSE_ADDR  12
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_IBIASP_SENSE_TERM  2
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_IBIASP_SENSE_NOM  1.2
#define AW_ATEST_TX_AFE_TX_DRIVER_BIAS_WA_IBIASP_SENSE_TOL  20

#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VSS_ADDR  13
#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VSS_TERM  4
#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VSS_NOM  0
#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VSS_TOL  20

#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VDDL_ADDR  14
#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VDDL_TERM  0
#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VDDL_NOM  0.75
#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VDDL_TOL  20

#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VREG_ADDR  15
#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VREG_TERM  0
#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VREG_NOM  0.75
#define AW_ATEST_TX_AFE_TX_DATAPATH_PA_VREG_TOL  20

#define AW_ATEST_TX_DCO_REG_VREF_ADDR  16
#define AW_ATEST_TX_DCO_REG_VREF_TERM  0
#define AW_ATEST_TX_DCO_REG_VREF_NOM  0.498
#define AW_ATEST_TX_DCO_REG_VREF_TOL  3

#define AW_ATEST_TX_DCO_REG_VOP_OUT_ADDR  17
#define AW_ATEST_TX_DCO_REG_VOP_OUT_TERM  0
#define AW_ATEST_TX_DCO_REG_VOP_OUT_NOM  0.691
#define AW_ATEST_TX_DCO_REG_VOP_OUT_TOL  20

#define AW_ATEST_TX_DCO_REG_VCHARGE_ADDR  18
#define AW_ATEST_TX_DCO_REG_VCHARGE_TERM  0
#define AW_ATEST_TX_DCO_REG_VCHARGE_NOM  0.405
#define AW_ATEST_TX_DCO_REG_VCHARGE_TOL  10

#define AW_ATEST_TX_DCO_REG_VDDREG_ADDR  19
#define AW_ATEST_TX_DCO_REG_VDDREG_TERM  0
#define AW_ATEST_TX_DCO_REG_VDDREG_NOM  0.751
#define AW_ATEST_TX_DCO_REG_VDDREG_TOL  5

#define AW_ATEST_TX_DCO_VCOBIAS_IOA_OSC_ADDR  20
#define AW_ATEST_TX_DCO_VCOBIAS_IOA_OSC_TERM  0
#define AW_ATEST_TX_DCO_VCOBIAS_IOA_OSC_NOM  0.219
#define AW_ATEST_TX_DCO_VCOBIAS_IOA_OSC_TOL  20

#define AW_ATEST_TX_BITCLK_REGULATOR_VOP_OUT_ADDR  21
#define AW_ATEST_TX_BITCLK_REGULATOR_VOP_OUT_TERM  0
#define AW_ATEST_TX_BITCLK_REGULATOR_VOP_OUT_NOM  0.8
#define AW_ATEST_TX_BITCLK_REGULATOR_VOP_OUT_TOL  20

#define AW_ATEST_TX_BITCLK_REGULATOR_VCHARGE_ADDR  22
#define AW_ATEST_TX_BITCLK_REGULATOR_VCHARGE_TERM  0
#define AW_ATEST_TX_BITCLK_REGULATOR_VCHARGE_NOM  0.405
#define AW_ATEST_TX_BITCLK_REGULATOR_VCHARGE_TOL  10

#define AW_ATEST_TX_BITCLK_REGULATOR_VDDREG_ADDR  23
#define AW_ATEST_TX_BITCLK_REGULATOR_VDDREG_TERM  0
#define AW_ATEST_TX_BITCLK_REGULATOR_VDDREG_NOM  0.751
#define AW_ATEST_TX_BITCLK_REGULATOR_VDDREG_TOL  5

#define AW_ATEST_TX_BITCLK_REGULATOR_VDDH_ADDR  24
#define AW_ATEST_TX_BITCLK_REGULATOR_VDDH_TERM  3
#define AW_ATEST_TX_BITCLK_REGULATOR_VDDH_NOM  1.2
#define AW_ATEST_TX_BITCLK_REGULATOR_VDDH_TOL  10

#define AW_ATEST_TX_BITCLK_REGULATOR_VSS_ADDR  25
#define AW_ATEST_TX_BITCLK_REGULATOR_VSS_TERM  4
#define AW_ATEST_TX_BITCLK_REGULATOR_VSS_NOM  0
#define AW_ATEST_TX_BITCLK_REGULATOR_VSS_TOL  10

#define AW_ATEST_TX_HSREF_REGULATOR_VREF_ADDR  26
#define AW_ATEST_TX_HSREF_REGULATOR_VREF_TERM  0
#define AW_ATEST_TX_HSREF_REGULATOR_VREF_NOM  0.498
#define AW_ATEST_TX_HSREF_REGULATOR_VREF_TOL  3

#define AW_ATEST_TX_HSREF_REGULATOR_VOP_OUT_ADDR  27
#define AW_ATEST_TX_HSREF_REGULATOR_VOP_OUT_TERM  0
#define AW_ATEST_TX_HSREF_REGULATOR_VOP_OUT_NOM  0.639
#define AW_ATEST_TX_HSREF_REGULATOR_VOP_OUT_TOL  20

#define AW_ATEST_TX_HSREF_REGULATOR_VCHARGE_ADDR  28
#define AW_ATEST_TX_HSREF_REGULATOR_VCHARGE_TERM  0
#define AW_ATEST_TX_HSREF_REGULATOR_VCHARGE_NOM  0.405
#define AW_ATEST_TX_HSREF_REGULATOR_VCHARGE_TOL  10

#define AW_ATEST_TX_HSREF_REGULATOR_VDDREG_ADDR  29
#define AW_ATEST_TX_HSREF_REGULATOR_VDDREG_TERM  0
#define AW_ATEST_TX_HSREF_REGULATOR_VDDREG_NOM  0.751
#define AW_ATEST_TX_HSREF_REGULATOR_VDDREG_TOL  5

#define AW_ATEST_TX_HSREF_REGULATOR_VDDH_ADDR  30
#define AW_ATEST_TX_HSREF_REGULATOR_VDDH_TERM  3
#define AW_ATEST_TX_HSREF_REGULATOR_VDDH_NOM  1.2
#define AW_ATEST_TX_HSREF_REGULATOR_VDDH_TOL  10

#define AW_ATEST_TX_HSREF_REGULATOR_VSS_ADDR  31
#define AW_ATEST_TX_HSREF_REGULATOR_VSS_TERM  4
#define AW_ATEST_TX_HSREF_REGULATOR_VSS_NOM  0
#define AW_ATEST_TX_HSREF_REGULATOR_VSS_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_B1_OA_B1_SFBIAS_200U_ADDR  1
#define AW_ATEST_RXA_AFE_RX_TIADC_B1_OA_B1_SFBIAS_200U_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_B1_OA_B1_SFBIAS_200U_NOM  0.88
#define AW_ATEST_RXA_AFE_RX_TIADC_B1_OA_B1_SFBIAS_200U_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_B1_PA_VDDREG_ADDR  2
#define AW_ATEST_RXA_AFE_RX_TIADC_B1_PA_VDDREG_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_B1_PA_VDDREG_NOM  0.75
#define AW_ATEST_RXA_AFE_RX_TIADC_B1_PA_VDDREG_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_B2_PA_VDDH_ADDR  3
#define AW_ATEST_RXA_AFE_RX_TIADC_B2_PA_VDDH_TERM  3
#define AW_ATEST_RXA_AFE_RX_TIADC_B2_PA_VDDH_NOM  1.2
#define AW_ATEST_RXA_AFE_RX_TIADC_B2_PA_VDDH_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_B2_PA_VSS_ADDR  4
#define AW_ATEST_RXA_AFE_RX_TIADC_B2_PA_VSS_TERM  4
#define AW_ATEST_RXA_AFE_RX_TIADC_B2_PA_VSS_NOM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_B2_PA_VSS_TOL  20

#define AW_ATEST_RXA_AFE_RX_TIADC_B2_IA_B2_BIAS_100U_ADDR  5
#define AW_ATEST_RXA_AFE_RX_TIADC_B2_IA_B2_BIAS_100U_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_B2_IA_B2_BIAS_100U_NOM  0.746
#define AW_ATEST_RXA_AFE_RX_TIADC_B2_IA_B2_BIAS_100U_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_B3_IA_IBIAS_B3_100U_ADDR  6
#define AW_ATEST_RXA_AFE_RX_TIADC_B3_IA_IBIAS_B3_100U_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_B3_IA_IBIAS_B3_100U_NOM  0.785
#define AW_ATEST_RXA_AFE_RX_TIADC_B3_IA_IBIAS_B3_100U_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_B3_PA_VDDL_ADDR  7
#define AW_ATEST_RXA_AFE_RX_TIADC_B3_PA_VDDL_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_B3_PA_VDDL_NOM  0.75
#define AW_ATEST_RXA_AFE_RX_TIADC_B3_PA_VDDL_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_ADDR  8
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_NOM  0.274
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_ADDR  9
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_TERM  4
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_NOM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_ADDR  10
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_NOM  0.765
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_2_ADDR  11
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_2_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_2_NOM  0.274
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_2_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_2_ADDR  12
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_2_TERM  4
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_2_NOM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_2_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_2_ADDR  13
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_2_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_2_NOM  0.765
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_2_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_3_ADDR  14
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_3_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_3_NOM  0.274
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IA_ADC_BIAS_50U_3_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_3_ADDR  15
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_3_TERM  4
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_3_NOM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_PA_VSS_3_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_3_ADDR  16
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_3_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_3_NOM  0.765
#define AW_ATEST_RXA_AFE_RX_TIADC_ADC_IOA_ADC_REF_CMN_3_TOL  10

#define AW_ATEST_RXA_AFE_RX_TIADC_B1_OA_VDRV_ADDR  17
#define AW_ATEST_RXA_AFE_RX_TIADC_B1_OA_VDRV_TERM  0
#define AW_ATEST_RXA_AFE_RX_TIADC_B1_OA_VDRV_NOM  0.75
#define AW_ATEST_RXA_AFE_RX_TIADC_B1_OA_VDRV_TOL  10

#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_OA_AFE_RX_CTLE_VGA_M_HV_ADDR  18
#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_OA_AFE_RX_CTLE_VGA_M_HV_TERM  0
#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_OA_AFE_RX_CTLE_VGA_M_HV_NOM  0.3
#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_OA_AFE_RX_CTLE_VGA_M_HV_TOL  10

#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_OA_AFE_RX_CTLE_VGA_P_HV_ADDR  19
#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_OA_AFE_RX_CTLE_VGA_P_HV_TERM  0
#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_OA_AFE_RX_CTLE_VGA_P_HV_NOM  0.299
#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_OA_AFE_RX_CTLE_VGA_P_HV_TOL  10

#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_WA_ATEST_BIAS_20U_ADDR  20
#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_WA_ATEST_BIAS_20U_TERM  1
#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_WA_ATEST_BIAS_20U_NOM  NC
#define AW_ATEST_RXA_AFE_RX_CTLE_VGA_ANA_TOP_WA_ATEST_BIAS_20U_TOL  10

#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_REF_P_ADDR  21
#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_REF_P_TERM  0
#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_REF_P_NOM  NC
#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_REF_P_TOL  50

#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_PKDET_REF_P_ADDR  22
#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_PKDET_REF_P_TERM  0
#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_PKDET_REF_P_NOM  0.045
#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_PKDET_REF_P_TOL  10

#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_PKDET_SIGNAL_ADDR  23
#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_PKDET_SIGNAL_TERM  0
#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_PKDET_SIGNAL_NOM  0
#define AW_ATEST_RXA_AFE_RX_SIGDET_ANA_TOP_PKDET_SIGNAL_TOL  10

#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_ITST_12P5U_ADDR  24
#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_ITST_12P5U_TERM  0
#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_ITST_12P5U_NOM  1.2
#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_ITST_12P5U_TOL  ?

#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_VBIAS_A_ADDR  25
#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_VBIAS_A_TERM  0
#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_VBIAS_A_NOM  0.091
#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_VBIAS_A_TOL  ?

#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_HYST_P_ADDR  26
#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_HYST_P_TERM  0
#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_HYST_P_NOM  0.039
#define AW_ATEST_RXA_AFE_RX_BSCAN_WA_HYST_P_TOL  ?

#define AW_ATEST_RXA_BITCLK_REGULATOR_VREF_ADDR  27
#define AW_ATEST_RXA_BITCLK_REGULATOR_VREF_TERM  0
#define AW_ATEST_RXA_BITCLK_REGULATOR_VREF_NOM  0.495
#define AW_ATEST_RXA_BITCLK_REGULATOR_VREF_TOL  10

#define AW_ATEST_RXA_BITCLK_REGULATOR_VOP_OUT_ADDR  28
#define AW_ATEST_RXA_BITCLK_REGULATOR_VOP_OUT_TERM  0
#define AW_ATEST_RXA_BITCLK_REGULATOR_VOP_OUT_NOM  0.713
#define AW_ATEST_RXA_BITCLK_REGULATOR_VOP_OUT_TOL  50

#define AW_ATEST_RXA_BITCLK_REGULATOR_VCHARGE_ADDR  29
#define AW_ATEST_RXA_BITCLK_REGULATOR_VCHARGE_TERM  0
#define AW_ATEST_RXA_BITCLK_REGULATOR_VCHARGE_NOM  0.405
#define AW_ATEST_RXA_BITCLK_REGULATOR_VCHARGE_TOL  10

#define AW_ATEST_RXA_BITCLK_REGULATOR_VDDREG_ADDR  30
#define AW_ATEST_RXA_BITCLK_REGULATOR_VDDREG_TERM  0
#define AW_ATEST_RXA_BITCLK_REGULATOR_VDDREG_NOM  0.75
#define AW_ATEST_RXA_BITCLK_REGULATOR_VDDREG_TOL  10

#define AW_ATEST_RXA_BITCLK_REGULATOR_VDDH_ADDR  31
#define AW_ATEST_RXA_BITCLK_REGULATOR_VDDH_TERM  3
#define AW_ATEST_RXA_BITCLK_REGULATOR_VDDH_NOM  1.2
#define AW_ATEST_RXA_BITCLK_REGULATOR_VDDH_TOL  10

#define AW_ATEST_RXB_BITCLK_REGULATOR_VSS_ADDR  1
#define AW_ATEST_RXB_BITCLK_REGULATOR_VSS_TERM  4
#define AW_ATEST_RXB_BITCLK_REGULATOR_VSS_NOM  0
#define AW_ATEST_RXB_BITCLK_REGULATOR_VSS_TOL  10

#define AW_ATEST_RXB_HSREF_REGULATOR_VREF_ADDR  2
#define AW_ATEST_RXB_HSREF_REGULATOR_VREF_TERM  0
#define AW_ATEST_RXB_HSREF_REGULATOR_VREF_NOM  0.496
#define AW_ATEST_RXB_HSREF_REGULATOR_VREF_TOL  10

#define AW_ATEST_RXB_HSREF_REGULATOR_VOP_OUT_ADDR  3
#define AW_ATEST_RXB_HSREF_REGULATOR_VOP_OUT_TERM  0
#define AW_ATEST_RXB_HSREF_REGULATOR_VOP_OUT_NOM  0.625
#define AW_ATEST_RXB_HSREF_REGULATOR_VOP_OUT_TOL  50

#define AW_ATEST_RXB_HSREF_REGULATOR_VCHARGE_ADDR  4
#define AW_ATEST_RXB_HSREF_REGULATOR_VCHARGE_TERM  0
#define AW_ATEST_RXB_HSREF_REGULATOR_VCHARGE_NOM  0.405
#define AW_ATEST_RXB_HSREF_REGULATOR_VCHARGE_TOL  10

#define AW_ATEST_RXB_HSREF_REGULATOR_VDDREG_ADDR  5
#define AW_ATEST_RXB_HSREF_REGULATOR_VDDREG_TERM  0
#define AW_ATEST_RXB_HSREF_REGULATOR_VDDREG_NOM  0.75
#define AW_ATEST_RXB_HSREF_REGULATOR_VDDREG_TOL  10

#define AW_ATEST_RXB_HSREF_REGULATOR_VDDH_ADDR  6
#define AW_ATEST_RXB_HSREF_REGULATOR_VDDH_TERM  3
#define AW_ATEST_RXB_HSREF_REGULATOR_VDDH_NOM  1.2
#define AW_ATEST_RXB_HSREF_REGULATOR_VDDH_TOL  10

#define AW_ATEST_RXB_HSREF_REGULATOR_VSS_ADDR  7
#define AW_ATEST_RXB_HSREF_REGULATOR_VSS_TERM  4
#define AW_ATEST_RXB_HSREF_REGULATOR_VSS_NOM  0
#define AW_ATEST_RXB_HSREF_REGULATOR_VSS_TOL  10

#define AW_ATEST_RXB_DCO_REG_VREF_ADDR  8
#define AW_ATEST_RXB_DCO_REG_VREF_TERM  0
#define AW_ATEST_RXB_DCO_REG_VREF_NOM  0.492
#define AW_ATEST_RXB_DCO_REG_VREF_TOL  10

#define AW_ATEST_RXB_DCO_REG_VOP_OUT_ADDR  9
#define AW_ATEST_RXB_DCO_REG_VOP_OUT_TERM  0
#define AW_ATEST_RXB_DCO_REG_VOP_OUT_NOM  0.97
#define AW_ATEST_RXB_DCO_REG_VOP_OUT_TOL  50

#define AW_ATEST_RXB_DCO_REG_VCHARGE_ADDR  10
#define AW_ATEST_RXB_DCO_REG_VCHARGE_TERM  0
#define AW_ATEST_RXB_DCO_REG_VCHARGE_NOM  0.405
#define AW_ATEST_RXB_DCO_REG_VCHARGE_TOL  10

#define AW_ATEST_RXB_DCO_REG_VDDREG_ADDR  11
#define AW_ATEST_RXB_DCO_REG_VDDREG_TERM  0
#define AW_ATEST_RXB_DCO_REG_VDDREG_NOM  0.93
#define AW_ATEST_RXB_DCO_REG_VDDREG_TOL  10

#define AW_ATEST_RXB_AFE_DIRECT_SYNTH_DCO_IOA_OSC_ADDR  12
#define AW_ATEST_RXB_AFE_DIRECT_SYNTH_DCO_IOA_OSC_TERM  0
#define AW_ATEST_RXB_AFE_DIRECT_SYNTH_DCO_IOA_OSC_NOM  0.225
#define AW_ATEST_RXB_AFE_DIRECT_SYNTH_DCO_IOA_OSC_TOL  20

extern const int cmn_size;
extern const char *cmn_atest_block_name[];
extern const char *cmn_atest_signal_name[];
extern const char *cmn_atest_block_addr[];
extern const char *cmn_atest_block_term[];
extern const char *cmn_atest_block_nom[];
extern const char *cmn_atest_block_tol[];
extern const int tx_size;
extern const char *tx_atest_block_name[];
extern const char *tx_atest_signal_name[];
extern const char *tx_atest_block_addr[];
extern const char *tx_atest_block_term[];
extern const char *tx_atest_block_nom[];
extern const char *tx_atest_block_tol[];
extern const int RXA_size;
extern const char *RXA_atest_block_name[];
extern const char *RXA_atest_signal_name[];
extern const char *RXA_atest_block_addr[];
extern const char *RXA_atest_block_term[];
extern const char *RXA_atest_block_nom[];
extern const char *RXA_atest_block_tol[];
extern const int RXB_size;
extern const char *RXB_atest_block_name[];
extern const char *RXB_atest_signal_name[];
extern const char *RXB_atest_block_addr[];
extern const char *RXB_atest_block_term[];
extern const char *RXB_atest_block_nom[];
extern const char *RXB_atest_block_tol[];







#define AW_ATEST_ADC_VREF_MV   (700)
#define AW_ATEST_ADC_VREF2_MV  (350)



#define AW_ATEST_ADC_VREF2_CONSTANT 350.0
#define AW_ATEST_ADC_MTEMP_CONSTANT 0.17


#endif
